apiVersion: v2
name: operaton
description: |
  Helm chart for Operaton
type: application
version: 1.0.4
appVersion: 1.0.0-beta-4
keywords:
  - bpm
  - bpmn
  - operaton
  - operaton-engine
  - dmn
  - process-engine
  - workflow
icon: https://operaton.github.io/operaton-helm/operaton-logo.png
home: https://operaton.org
sources:
  - https://github.com/operaton/operaton-helm/tree/main/charts/operaton
  - https://github.com/operaton/operaton-docker
  - https://github.com/operaton/operaton
maintainers:
  - name: Jaye
    url: https://github.com/jmaster1985
annotations:
  artifacthub.io/links: |
    - name: Operaton BPM Helm chart
      url: https://github.com/operaton/operaton-helm/tree/main/charts/operaton
    - name: Operaton BPM Docker
      url: https://github.com/operaton/operaton-docker
    - name: Operaton BPM
      url: https://github.com/operaton/operaton
  # This will be generated automatically by the release workflow.
  # https://github.com/operaton/operaton-helm/blob/main/.github/workflows/release.yaml
  artifacthub.io/changes: |
